dbt_bigquery_prad88:
  outputs:
    dev:
      dataset: bqdbt_dw
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('KEY_FILE') }}"
      location: US
      method: service-account
      priority: interactive
      project: bqdbt-422813
      threads: 1
      type: bigquery
  target: dev
